# Generated by Django 2.2.1 on 2019-05-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_time', models.DateTimeField()),
                ('mark', models.CharField(max_length=50)),
                ('keyword', models.CharField(max_length=50)),
            ],
        ),
    ]
